# Generated by Django 3.0.5 on 2020-04-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_category', models.CharField(choices=[('H', 'Health'), ('F', 'Finance'), ('C', 'Household')], max_length=2)),
                ('advice_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(max_length=1000)),
                ('task_achieved', models.CharField(choices=[('AC', 'Task Achieved'), ('NC', 'Task Not Achieved')], default='NC', max_length=2)),
                ('task_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=3000)),
                ('user_taskList', models.CharField(max_length=3000)),
                ('user_adviceList', models.CharField(max_length=3000)),
                ('task_achieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Task')),
            ],
        ),
    ]
