# Generated by Django 3.0.5 on 2020-04-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_text',
            field=models.TextField(default=' task '),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
